### ISSUE TITLE
Формат описания packagedef

### ISSUE THREAD

**Issue by Khorevaa** [oscript-library/opm#39]
Как разработчит хочу иметь возможность указывать настройки пакета в формате yamk

```
name: YAML 
version: 0.0.1
description: Конвертация и чтение в формат YAML
executable: 
    class: 'yaml2.os'
engine-version: '*'
include-content:
    - 'src/*'
    - 'tests/*'
    - 'bin/*'
    - readme.md
explicit-modules:
    - '*'
keywords:
    - null
repository:
    type: git
    url: ..
author:
    name: Автор
    email: Почта
    url: url
depends-on:
    logos: 1.1.0
    cmdline: ^3.0.6
    tempfiles: '^3.4.3"'
    tool1cd: ^2.0.0
    v8runner: ^4.0.0
    strings: '*'
```
